/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
import Carousel from '../components/Carousel';
import ContentBlock from '../components/ContentBlock';
import CtaBlock from '../components/CtaBlock';
import CtaSection from '../components/CtaSection';
import Hero from '../components/Hero';
import MapBlock from '../components/MapBlock';
import PricingSection from '../components/PricingSection';
import Speakers from '../components/Speakers';
import TeaserSection from '../components/TeaserSection';
import VideoBlock from '../components/VideoBlock';
import WaveSplitter from '../components/WaveSplitter';

const components = new Map();
components.set('Carousel', Carousel);
components.set('ContentBlock', ContentBlock);
components.set('CtaBlock', CtaBlock);
components.set('CtaSection', CtaSection);
components.set('Hero', Hero);
components.set('MapBlock', MapBlock);
components.set('PricingSection', PricingSection);
components.set('Speakers', Speakers);
components.set('TeaserSection', TeaserSection);
components.set('VideoBlock', VideoBlock);
components.set('WaveSplitter', WaveSplitter);

export default function componentFactory(componentName: any) {
  return components.get(componentName);
};
